begin;
set constraints all immediate;
alter table spicy_settings add column robots text;
insert into spicy_settings values (2,'','','','','f','f','','',3,(select robots from seo_chunks where site_id = 3));
insert into spicy_settings values (3,'','','','','f','f','','',2,(select robots from seo_chunks where site_id = 2));
insert into spicy_settings values (4,'','','','','f','f','','',18,(select robots from seo_chunks where site_id = 18));
UPDATE spicy_settings SET robots = (select robots from seo_chunks where site_id = 1) where site_id = 1;
commit;
begin;
set constraints all immediate;
alter table spicy_settings alter column robots set not null;
ALTER TABLE seo_chunks DROP COLUMN robots;
commit;
